[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
degen_terminal = "5Kq43SR2HUNsyNZWaau1p8kQzAvW2UA2mAvempdchTrk"

[programs.localnet]
degen_terminal = "5Kq43SR2HUNsyNZWaau1p8kQzAvW2UA2mAvempdchTrk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/alexd/.config/solana/deployer.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
